map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
foreground #1E90FF
cursor #104E8B
selection_foreground #000000
selection_background #1A5F9C
background_opacity 0.7
enable_audio_bell no
wayland_enable_ime yes
